//
//  EnumModel.swift
//
//  Generated by IBM Bluemix Mobile DevEx.
//


import Foundation
import ObjectMapper


public class EnumModel: Mappable {


    /// 
    public var stringEnum: stringenum?
    /// 
    public var floatEnum: floatenum?
    /// 
    public var doubleEnum: doubleenum?
    /// 
    public var integerEnum: integerenum?
    /// 
    public var longEnum: longenum?

    public enum stringenum: String {

        case xvii = "xvii"
        case xix = "xix"
    }

    public enum floatenum: Float {

        case number17 = 1.7
        case number19 = 1.9
    }

    public enum doubleenum: Double {

        case number17 = 1.7
        case number19 = 1.9
    }

    public enum integerenum: Int {

        case number17 = 17
        case number19 = 19
    }

    public enum longenum: Int64 {

        case number17 = 17
        case number19 = 19
    }

    public init() {}


    // MARK: ObjectMapper

    required public init?(map: Map) { }

    public func mapping(map: Map) {

        self.stringEnum <- map["stringEnum"]
        self.floatEnum <- map["floatEnum"]
        self.doubleEnum <- map["doubleEnum"]
        self.integerEnum <- map["integerEnum"]
        self.longEnum <- map["longEnum"]
    }

}
