//
//  FormModel.swift
//
//  Generated by IBM Bluemix Mobile DevEx.
//


import Foundation
import ObjectMapper


public class FormModel: Mappable {


    /// 
    public var formString: String?
    /// 
    public var formFloat: Float?
    /// 
    public var formDouble: Double?
    /// 
    public var formInteger: Int?
    /// 
    public var formLong: Int64?
    /// 
    public var formBoolean: Bool?
    /// 
    public var formCSV: [String]?
    /// 
    public var formSSV: [String]?
    /// 
    public var formTSV: [String]?
    /// 
    public var formPipes: [String]?
    /// 
    public var formMulti: [String]?
    /// 
    public var formDate: Date?
    /// 
    public var formDateTime: Date?

    public init() {}


    // MARK: ObjectMapper

    required public init?(map: Map) { }

    public func mapping(map: Map) {

        self.formString <- map["formString"]
        self.formFloat <- map["formFloat"]
        self.formDouble <- map["formDouble"]
        self.formInteger <- map["formInteger"]
        self.formLong <- map["formLong"]
        self.formBoolean <- map["formBoolean"]
        self.formCSV <- map["formCSV"]
        self.formSSV <- map["formSSV"]
        self.formTSV <- map["formTSV"]
        self.formPipes <- map["formPipes"]
        self.formMulti <- map["formMulti"]
        self.formDate <- map["formDate"]
        self.formDateTime <- map["formDateTime"]
    }

}
