//
//  HeaderModel.swift
//
//  Generated by IBM Bluemix Mobile DevEx.
//


import Foundation
import ObjectMapper


public class HeaderModel: Mappable {


    /// 
    public var headerString: String?
    /// 
    public var headerFloat: Float?
    /// 
    public var headerDouble: Double?
    /// 
    public var headerInteger: Int?
    /// 
    public var headerLong: Int64?
    /// 
    public var headerBoolean: Bool?
    /// 
    public var headerCSV: [String]?
    /// 
    public var headerSSV: [String]?
    /// 
    public var headerTSV: [String]?
    /// 
    public var headerPipes: [String]?
    /// 
    public var headerDate: Date?
    /// 
    public var headerDateTime: Date?

    public init() {}


    // MARK: ObjectMapper

    required public init?(map: Map) { }

    public func mapping(map: Map) {

        self.headerString <- map["headerString"]
        self.headerFloat <- map["headerFloat"]
        self.headerDouble <- map["headerDouble"]
        self.headerInteger <- map["headerInteger"]
        self.headerLong <- map["headerLong"]
        self.headerBoolean <- map["headerBoolean"]
        self.headerCSV <- map["headerCSV"]
        self.headerSSV <- map["headerSSV"]
        self.headerTSV <- map["headerTSV"]
        self.headerPipes <- map["headerPipes"]
        self.headerDate <- map["headerDate"]
        self.headerDateTime <- map["headerDateTime"]
    }

}
