//
//  PathModel.swift
//
//  Generated by IBM Bluemix Mobile DevEx.
//


import Foundation
import ObjectMapper


public class PathModel: Mappable {


    /// 
    public var pathString: String?
    /// 
    public var pathFloat: Float?
    /// 
    public var pathDouble: Double?
    /// 
    public var pathInteger: Int?
    /// 
    public var pathLong: Int64?
    /// 
    public var pathBoolean: Bool?
    /// 
    public var pathCSV: [String]?
    /// 
    public var pathSSV: [String]?
    /// 
    public var pathTSV: [String]?
    /// 
    public var pathPipes: [String]?

    public init() {}


    // MARK: ObjectMapper

    required public init?(map: Map) { }

    public func mapping(map: Map) {

        self.pathString <- map["pathString"]
        self.pathFloat <- map["pathFloat"]
        self.pathDouble <- map["pathDouble"]
        self.pathInteger <- map["pathInteger"]
        self.pathLong <- map["pathLong"]
        self.pathBoolean <- map["pathBoolean"]
        self.pathCSV <- map["pathCSV"]
        self.pathSSV <- map["pathSSV"]
        self.pathTSV <- map["pathTSV"]
        self.pathPipes <- map["pathPipes"]
    }

}
