//
//  QueryModel.swift
//
//  Generated by IBM Bluemix Mobile DevEx.
//


import Foundation
import ObjectMapper


public class QueryModel: Mappable {


    /// 
    public var queryString: String?
    /// 
    public var queryFloat: Float?
    /// 
    public var queryDouble: Double?
    /// 
    public var queryInteger: Int?
    /// 
    public var queryLong: Int64?
    /// 
    public var queryBoolean: Bool?
    /// 
    public var queryCSV: [String]?
    /// 
    public var querySSV: [String]?
    /// 
    public var queryTSV: [String]?
    /// 
    public var queryPipes: [String]?
    /// 
    public var queryMulti: [String]?
    /// 
    public var queryDate: Date?
    /// 
    public var queryDateTime: Date?

    public init() {}


    // MARK: ObjectMapper

    required public init?(map: Map) { }

    public func mapping(map: Map) {

        self.queryString <- map["queryString"]
        self.queryFloat <- map["queryFloat"]
        self.queryDouble <- map["queryDouble"]
        self.queryInteger <- map["queryInteger"]
        self.queryLong <- map["queryLong"]
        self.queryBoolean <- map["queryBoolean"]
        self.queryCSV <- map["queryCSV"]
        self.querySSV <- map["querySSV"]
        self.queryTSV <- map["queryTSV"]
        self.queryPipes <- map["queryPipes"]
        self.queryMulti <- map["queryMulti"]
        self.queryDate <- map["queryDate"]
        self.queryDateTime <- map["queryDateTime"]
    }

}
